---
title: "Interactive 3D plot"
author: "Jung-Jin Lee"
date: '2018-12-06'
slug: interactive-3d-plot
tags: []
categories: []
---

```{r, echo = F}
knitr::opts_chunk$set(
  echo = F,
  message = F
)
```

Interactive 3D plot created using `plotly`:

<<<<<<< HEAD
```{r, echo = T}
=======
```{r}
>>>>>>> 37731c382700905011424f1a0a8f69a446495b12
library(plotly)

mtcars$am[which(mtcars$am == 0)] <- 'Automatic'
mtcars$am[which(mtcars$am == 1)] <- 'Manual'
mtcars$am <- as.factor(mtcars$am)

p <- plot_ly(mtcars, x = ~wt, y = ~hp, z = ~qsec, color = ~am, colors = c('#BF382A', '#0C4B8E')) %>%
  add_markers() %>%
  layout(scene = list(xaxis = list(title = 'Weight'),
                     yaxis = list(title = 'Gross horsepower'),
                     zaxis = list(title = '1/4 mile time')))
<<<<<<< HEAD
=======

# Create a shareable link to your chart
# Set up API credentials: https://plot.ly/r/getting-started
#chart_link = api_create(p, filename="scatter3d-basic")
#chart_link
>>>>>>> 37731c382700905011424f1a0a8f69a446495b12
p
```
